export const posts = [
  {
    id: 1,
    title: "5 Premium Theme for React",
    img: "https://images.pexels.com/photos/7963572/pexels-photo-7963572.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit ad optio magnam veniam nihil, quasi in architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea?",
    longDesc:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit ad optio magnam veniam nihil, quasi in architecto dignissimosrerum, soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea? Lorem ipsum dolor sit amet, consecteturadipisicing elit.Velit ad optio magnam veniam nihil, quasi in architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendiadipisci possimus pariatur dolorem ea? Lorem ipsum dolor sit amet, consectetur adipisicing elit.Velit ad optio magnam veniamnihil, quasi in architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea? Loremipsum dolor sit amet, consectetur adipisicing elit.Velit ad optio magnam veniam nihil, quasi in architecto dignissimos rerum,soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea?Lorem ipsum dolor sit amet, consectetur adipisicingelit.Velit ad optio magnam veniam nihil, quasi architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendi adipiscipossimus pariatur dolorem ea? Lorem ipsum dolor sit amet, consectetur adipisicing elit.Velit optio magnam veniam nihil,quasi in architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea? Loremipsum dolor sit amet, consectetur adipisicing elVelit ad optio magnam veniam nihil, quasi in architecto dignissimos rerum,soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea? Lorem ipsum dolor sit amet, consectetur adipisicingelit.Velit ad optio magnam veniam nihil, quain architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendi adipiscipossimus pariatur dolorem ea?"
  },
  {
    id: 2,
    title: "How to animate elements",
    img: "https://inspirationandmore.com/wp-content/uploads/2022/10/Quotes-768x432.jpg",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit ad optio magnam veniam nihil, quasi in architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea?",
    longDesc:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit ad optio magnam veniam nihil, quasi in architecto dignissimosrerum, soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea? Lorem ipsum dolor sit amet, consecteturadipisicing elit.Velit ad optio magnam veniam nihil, quasi in architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendiadipisci possimus pariatur dolorem ea? Lorem ipsum dolor sit amet, consectetur adipisicing elit.Velit ad optio magnam veniamnihil, quasi in architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea? Loremipsum dolor sit amet, consectetur adipisicing elit.Velit ad optio magnam veniam nihil, quasi in architecto dignissimos rerum,soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea?Lorem ipsum dolor sit amet, consectetur adipisicingelit.Velit ad optio magnam veniam nihil, quasi architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendi adipiscipossimus pariatur dolorem ea? Lorem ipsum dolor sit amet, consectetur adipisicing elit.Velit optio magnam veniam nihil,quasi in architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea? Loremipsum dolor sit amet, consectetur adipisicing elVelit ad optio magnam veniam nihil, quasi in architecto dignissimos rerum,soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea? Lorem ipsum dolor sit amet, consectetur adipisicingelit.Velit ad optio magnam veniam nihil, quain architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendi adipiscipossimus pariatur dolorem ea?"
  },
  {
    id: 3,
    title: "Learn JS in 30 days",
    img: "https://media.licdn.com/dms/image/C4D22AQEFRNs9nT20BQ/feedshare-shrink_2048_1536/0/1581605142465?e=2147483647&v=beta&t=v5NIDou6-9jha2pIX3fAZXuEH0wIP2Lhpm1Tgqd6-5I",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit ad optio magnam veniam nihil, quasi in architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea?",
    longDesc:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit ad optio magnam veniam nihil, quasi in architecto dignissimosrerum, soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea? Lorem ipsum dolor sit amet, consecteturadipisicing elit.Velit ad optio magnam veniam nihil, quasi in architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendiadipisci possimus pariatur dolorem ea? Lorem ipsum dolor sit amet, consectetur adipisicing elit.Velit ad optio magnam veniamnihil, quasi in architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea? Loremipsum dolor sit amet, consectetur adipisicing elit.Velit ad optio magnam veniam nihil, quasi in architecto dignissimos rerum,soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea?Lorem ipsum dolor sit amet, consectetur adipisicingelit.Velit ad optio magnam veniam nihil, quasi architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendi adipiscipossimus pariatur dolorem ea? Lorem ipsum dolor sit amet, consectetur adipisicing elit.Velit optio magnam veniam nihil,quasi in architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea? Loremipsum dolor sit amet, consectetur adipisicing elVelit ad optio magnam veniam nihil, quasi in architecto dignissimos rerum,soluta ipsa nobis eos mollitia eligendi adipisci possimus pariatur dolorem ea? Lorem ipsum dolor sit amet, consectetur adipisicingelit.Velit ad optio magnam veniam nihil, quain architecto dignissimos rerum, soluta ipsa nobis eos mollitia eligendi adipiscipossimus pariatur dolorem ea?"
  }
]
